"""Iteration orchestration for the automated command proposer path."""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

from autoharness.config.models import ExperimentConfig
from autoharness.context.builder import build_proposer_context
from autoharness.proposer.base import run_proposer
from autoharness.proposer.session import write_proposer_session_artifacts
from autoharness.reporting.final_report import write_final_report
from autoharness.reporting.summary import write_run_summary
from autoharness.runners.base import SplitRunResult
from autoharness.runners.pytest_runner import run_pytest_split
from autoharness.runners.script_runner import run_script_split
from autoharness.selection.policy import CandidateStats, SelectionDecision, select_candidate
from autoharness.store.ledger import append_ledger_event
from autoharness.store.frontier import write_frontier_state
from autoharness.store.query import load_frontier, load_split_cases, load_split_summary
from autoharness.store.writer import write_json, write_text
from autoharness.surfaces.diff import write_candidate_diff
from autoharness.surfaces.materialize import (
    copy_editable_surfaces_to_workspace,
    snapshot_candidate_surfaces_from_workspace,
    snapshot_surface_files,
    snapshot_surface_files_from_source,
)
from autoharness.validation.base import ValidationResult
from autoharness.validation.script import validate_script
from autoharness.validation.python import validate_python_import


@dataclass(frozen=True)
class IterationResult:
    candidate_id: str
    candidate_dir: Path
    candidate_workspace: Path
    promoted: bool
    status: str
    reason: str
    validation: ValidationResult
    train: SplitRunResult | None = None
    holdout: SplitRunResult | None = None


def run_iteration(
    config: ExperimentConfig,
    run_dir: Path,
    iteration_index: int,
    champion_candidate_id: str,
    champion_workspace_root: Path,
    champion_changed_file_count: int = 0,
) -> IterationResult:
    candidate_id = f"iter_{iteration_index:03d}_cand_a"
    candidate_dir = run_dir / "candidates" / candidate_id
    proposer_workspace = run_dir / "proposer_sessions" / candidate_id
    editable_dir = proposer_workspace / "editable"
    candidate_workspace = run_dir / "workspaces" / candidate_id
    ledger_path = run_dir / "ledger.jsonl"

    editable_paths = _stage_editable_surfaces(
        config=config,
        run_dir=run_dir,
        source_candidate_id=champion_candidate_id,
        editable_dir=editable_dir,
    )
    build_proposer_context(
        config=config,
        run_dir=run_dir,
        proposer_workspace=proposer_workspace,
        editable_relative_paths=[
            str(path.relative_to(proposer_workspace)) for path in editable_paths
        ],
        champion_candidate_id=champion_candidate_id,
    )
    proposer_result = run_proposer(config.proposer, proposer_workspace, editable_paths)
    write_proposer_session_artifacts(
        candidate_dir / "proposer",
        stdout=str(proposer_result.metadata.get("stdout", "")),
        stderr=str(proposer_result.metadata.get("stderr", "")),
        metadata=proposer_result.metadata,
    )
    write_json(candidate_dir / "proposer" / "result.json", proposer_result)
    write_text(
        candidate_dir / "hypothesis.md",
        "Automated candidate generated by the command proposer backend.",
    )
    append_ledger_event(
        ledger_path,
        "proposer_completed",
        {
            "candidate_id": candidate_id,
            "changed_files": [str(path.relative_to(proposer_workspace)) for path in proposer_result.changed_files],
            "returncode": proposer_result.metadata.get("returncode"),
        },
    )
    if proposer_result.metadata.get("returncode") != 0:
        append_ledger_event(
            ledger_path,
            "candidate_discarded",
            {"candidate_id": candidate_id, "reason": "proposer_failed"},
        )
        return IterationResult(
            candidate_id=candidate_id,
            candidate_dir=candidate_dir,
            candidate_workspace=candidate_workspace,
            promoted=False,
            status="discarded",
            reason="proposer_failed",
            validation=ValidationResult(False, "Proposer command failed."),
        )

    _materialize_candidate_workspace(champion_workspace_root, candidate_workspace)
    copy_editable_surfaces_to_workspace(config.surfaces, editable_dir, candidate_workspace)
    snapshot_candidate_surfaces_from_workspace(
        surfaces=config.surfaces,
        workspace_root=candidate_workspace,
        editable_dir=editable_dir,
        destination_dir=candidate_dir / "surfaces",
    )
    write_candidate_diff(
        surfaces=config.surfaces,
        previous_dir=run_dir / "candidates" / champion_candidate_id / "surfaces",
        current_dir=candidate_dir / "surfaces",
        output_path=candidate_dir / "diffs" / "unified.patch",
    )
    write_json(
        candidate_dir / "meta.json",
        {
            "candidate_id": candidate_id,
            "surface_count": len(config.surfaces),
        },
    )

    validation = _run_validation(config, candidate_workspace)
    write_json(candidate_dir / "validation" / "result.json", validation)
    if not validation.ok:
        append_ledger_event(
            ledger_path,
            "candidate_discarded",
            {"candidate_id": candidate_id, "reason": "validation_failed"},
        )
        return IterationResult(
            candidate_id=candidate_id,
            candidate_dir=candidate_dir,
            candidate_workspace=candidate_workspace,
            promoted=False,
            status="discarded",
            reason="validation_failed",
            validation=validation,
        )

    train_result = _run_split(config, "train", candidate_workspace, candidate_dir)
    holdout_required_now = _should_run_holdout(config, iteration_index)
    holdout_result = (
        _run_split(config, "holdout", candidate_workspace, candidate_dir)
        if holdout_required_now
        else None
    )
    champion_train = _load_split_summary(run_dir, champion_candidate_id, "train")
    champion_holdout = _load_split_summary(run_dir, champion_candidate_id, "holdout")
    champion_holdout_cases = load_split_cases(run_dir, champion_candidate_id, "holdout")
    assert champion_train is not None
    assert train_result is not None
    decision = select_candidate(
        policy=config.policy,
        champion=CandidateStats(
            train=champion_train,
            holdout=champion_holdout,
            holdout_cases=champion_holdout_cases,
            changed_file_count=champion_changed_file_count,
        ),
        candidate=CandidateStats(
            train=train_result.summary,
            holdout=holdout_result.summary if holdout_result else None,
            holdout_cases=holdout_result.cases if holdout_result else None,
            changed_file_count=len(proposer_result.changed_files),
        ),
        holdout_required_now=holdout_required_now and config.policy.require_holdout_for_promotion,
        allow_promotion_without_holdout=not config.policy.require_holdout_for_promotion,
    )

    append_ledger_event(
        ledger_path,
        _decision_event_type(decision),
        {"candidate_id": candidate_id, "reason": decision.reason},
    )
    current_frontier = load_frontier(run_dir)
    champion_for_frontier = candidate_id if decision.promoted else champion_candidate_id
    write_frontier_state(
        run_dir,
        champion_candidate_id=champion_for_frontier,
        primary_metric=config.policy.primary_metric,
        keep_top_k_visible_candidates=config.policy.keep_top_k_visible_candidates,
        baseline_validation_ok=bool(current_frontier.get("baseline_validation_ok", True)),
    )
    write_run_summary(run_dir)
    write_final_report(run_dir)

    return IterationResult(
        candidate_id=candidate_id,
        candidate_dir=candidate_dir,
        candidate_workspace=candidate_workspace,
        promoted=decision.promoted,
        status=decision.status,
        reason=decision.reason,
        validation=validation,
        train=train_result,
        holdout=holdout_result,
    )


def _materialize_candidate_workspace(source_workspace: Path, destination_workspace: Path) -> None:
    if destination_workspace.exists():
        shutil.rmtree(destination_workspace)
    shutil.copytree(
        source_workspace,
        destination_workspace,
        ignore=shutil.ignore_patterns(
            "runs",
            ".venv",
            "__pycache__",
            ".pytest_cache",
            "*.pyc",
        ),
    )


def _run_validation(config: ExperimentConfig, workspace_root: Path) -> ValidationResult:
    if config.validation.kind == "python_import":
        return validate_python_import(workspace_root, config.validation.entrypoint or "")
    if config.validation.kind == "script" and config.validation.script:
        return validate_script(
            workspace_root,
            config.validation.script,
            timeout_sec=config.validation.timeout_sec,
        )
    return ValidationResult(False, f"Validation kind '{config.validation.kind}' is not implemented yet.")


def _run_split(
    config: ExperimentConfig,
    split: str,
    workspace_root: Path,
    candidate_dir: Path,
) -> SplitRunResult | None:
    if config.runner.kind == "pytest":
        return run_pytest_split(
            config=config,
            split=split,
            workspace_root=workspace_root,
            output_dir=candidate_dir / "eval" / split,
        )
    if config.runner.kind == "script":
        return run_script_split(
            config=config,
            split=split,
            workspace_root=workspace_root,
            output_dir=candidate_dir / "eval" / split,
        )
    return None


def _load_split_summary(run_dir: Path, candidate_id: str, split: str):
    return load_split_summary(run_dir, candidate_id, split)


def _stage_editable_surfaces(
    config: ExperimentConfig,
    run_dir: Path,
    source_candidate_id: str,
    editable_dir: Path,
) -> list[Path]:
    source_surfaces_dir = run_dir / "candidates" / source_candidate_id / "surfaces"
    if source_surfaces_dir.exists():
        return snapshot_surface_files_from_source(
            surfaces=config.surfaces,
            source_dir=source_surfaces_dir,
            destination_dir=editable_dir,
        )
    return snapshot_surface_files(config.surfaces, editable_dir)


def _should_run_holdout(config: ExperimentConfig, iteration_index: int) -> bool:
    if config.policy.holdout_every <= 1:
        return True
    return iteration_index % config.policy.holdout_every == 0


def _decision_event_type(decision: SelectionDecision) -> str:
    if decision.status == "promoted":
        return "candidate_promoted"
    if decision.status == "screened_in":
        return "candidate_screened_in"
    return "candidate_discarded"
